name: Build & Release mEdge 2.0
on:
  workflow_dispatch:
  push:
    tags: ['v1.0.2']

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm install
      - name: Build app
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: dist/**
          if-no-files-found: ignore
